add TESTING to skip certain tests and email

diff --git a/root-daily b/root-daily
--- a/root-daily
+++ b/root-daily
@@ -7,26 +7,40 @@ LOG="/home/viyadep/daily.log"
 TMPD="/tmp/daily.today"
 NOW="/home/viyadep/checkstatus.now"
 
+# set up so we don't necessarily send out email:
+# and do a bunch of other things:
+TESTING=0
+if [ $1 == '-t' ]; then
+    TESTING=1
+    TMPD='/dev/stdout'
+fi
+
 # this is used while dmtransformservices is flagged 'down' by all-services,
 # but nothing else says it is:
 SVCIGNORE='sas-viya-dmtransformservices-default'
 
-# first, clean space in /dmo1/prod/temp and /dmo1/dev/temp and /analytics1:
-if [ "$HOSTNAME" == "sasdevcontrollerrhelsr01.corp.local" ]; then
-    /bin/find /dmo1/prod/temp -name ".nfs*" -mtime +1 -exec rm -f {} \;
-    /bin/find /dmo1/dev/temp  -name ".nfs*" -mtime +1 -exec rm -f {} \;
-    /bin/find /analytics1     -name ".nfs*" -mtime +1 -exec rm -f {} \;
+if [ $TESTING -eq 0 ]; then
+    # first, clean space in /dmo1/prod/temp and /dmo1/dev/temp and /analytics1:
+    if [ "$HOSTNAME" == "sasdevcontrollerrhelsr01.corp.local" ]; then
+        /bin/find /dmo1/prod/temp -name ".nfs*" -mtime +1 -exec rm -f {} \;
+        /bin/find /dmo1/dev/temp  -name ".nfs*" -mtime +1 -exec rm -f {} \;
+        /bin/find /analytics1     -name ".nfs*" -mtime +1 -exec rm -f {} \;
+    fi
 fi
 
-# then, if we are one of the microservers, run the cleanwork process:
-echo ${HOSTNAME} | grep -q 'microrhelsr01' 
-if [ $? -eq 0 ]; then
-    /root/bin/daily_cleanup.sh
+if [ $TESTING -eq 0 ]; then
+    # then, if we are one of the microservers, run the cleanwork process:
+    echo ${HOSTNAME} | grep -q 'microrhelsr01' 
+    if [ $? -eq 0 ]; then
+        /root/bin/daily_cleanup.sh
+    fi
 fi
 
-# we only want to do this from micro1:
-if [ "$HOSTNAME" == "sasmicrorhelsr01.corp.local" ]; then
-    rsync -a "/mnt/dropzone/HR/UnapprovedTimeSheets/" "/dmo1/prod/dropZone/UnapprovedTimeSheetNotifications"
+if [ $TESTING -eq 0 ]; then
+    # we only want to do this from micro1:
+    if [ "$HOSTNAME" == "sasmicrorhelsr01.corp.local" ]; then
+        rsync -a "/mnt/dropzone/HR/UnapprovedTimeSheets/" "/dmo1/prod/dropZone/UnapprovedTimeSheetNotifications"
+    fi
 fi
 
 # gather system info:
@@ -52,14 +66,15 @@ echo    >>${TMPD}
 
 # network connectivity:
 /home/viyadep/bin/sysping >>${TMPD}
-echo    >>${TMPD}
+echo >>${TMPD}
 
 # sas-viya-all-services status to checkstatus.now:
 service sas-viya-all-services status >${NOW}
 
 # --- see if anyone is down:
 echo -n "services check: " >>${TMPD}
-grep -q 'down' | grep -v ${SVCIGNORE} ${NOW}
+grep -v ${SVCIGNORE} ${NOW} | grep -q 'down'
+
 if [ $? -eq 0 ]; then
     echo "some services are DOWN:" >>${TMPD}
     grep -i 'down' ${NOW} | grep -v ${SVCIGNORE} >>${TMPD}
@@ -85,46 +100,52 @@ echo    >>${TMPD}
 echo "-------------------------------------------------------------------------------------------" >>${TMPD}
 echo    >>${TMPD}
 
-# --- add new daily output to daily.log:
-cat ${TMPD} >>${LOG}
+if [ $TESTING -eq 0 ]; then
+    # --- add new daily output to daily.log:
+    cat ${TMPD} >>${LOG}
+fi
 
 # --- change ownership of the ${NOW} file:
 chown viyadep.viyadep ${NOW}
 
 # --- send the new output to the main destination:
-mail -s "daily report from $HOSTNAME" viyadep@sasdevcontrollerrhelsr01 <${TMPD}
-rm -f ${TMPD}
+if [ $TESTING -eq 0 ]; then
+    mail -s "daily report from $HOSTNAME" viyadep@sasdevcontrollerrhelsr01 <${TMPD}
+    rm -f ${TMPD}
+fi
 
 # --- other things:
-if [ -d /home/viyadep/incoming/work ]; then
-    YESTERDAY=`date -d 'yesterday' '+%Y-%m-%d'`
-    LOGFILECOUNT=`ls /analytics1/logs | grep stillwell1-${YESTERDAY} | wc -l`
-    FILES=`/usr/bin/find /analytics1/logs -name stillwell1-${YESTERDAY}*`
-    OUT="/home/viyadep/incoming/work/stillwell.out"
-    FAIL=0
+if [ $TESTING -eq 0 ]; then
+    if [ -d /home/viyadep/incoming/work ]; then
+        YESTERDAY=`date -d 'yesterday' '+%Y-%m-%d'`
+        LOGFILECOUNT=`ls /analytics1/logs | grep stillwell1-${YESTERDAY} | wc -l`
+        FILES=`/usr/bin/find /analytics1/logs -name stillwell1-${YESTERDAY}*`
+        OUT="/home/viyadep/incoming/work/stillwell.out"
+        FAIL=0
 
-    for f in ${FILES}; do
-        grep -q 'Exit code: 0' ${f}
-        if [ $? -ne 0 ]; then
-            FAIL=1
-            echo "the twice-daily Stillwell1.bat file failed on SASOA.corp.local on ${YESTERDAY}:" >>${OUT}
-            echo "${f} failed" >>${OUT}
+        for f in ${FILES}; do
+            grep -q 'Exit code: 0' ${f}
+            if [ $? -ne 0 ]; then
+                FAIL=1
+                echo "the twice-daily Stillwell1.bat file failed on SASOA.corp.local on ${YESTERDAY}:" >>${OUT}
+                echo "${f} failed" >>${OUT}
+                echo >>${OUT}
+            fi
+        done
+
+        if [ ${LOGFILECOUNT} -lt 2 ]; then
+            echo "Stillwell1.bat ran ${LOGFILECOUNT} time(s) on ${YESTERDAY}:" >>${OUT}
+            echo 'ls /analytics1/logs/stillwell1-${YESTERDAY}*:' >>${OUT}
+            ls /analytics1/logs/stillwell1-${YESTERDAY}* >>${OUT}
             echo >>${OUT}
+        elif [ ${FAIL} -eq 0 ]; then
+            echo "Stillwell1.bat ran successfully on ${YESTERDAY}" >>${OUT}
+        else
+            echo "Stillwell1.bat failure ${YESTERDAY}" >>${OUT}
         fi
-    done
 
-    if [ ${LOGFILECOUNT} -lt 2 ]; then
-        echo "Stillwell1.bat ran ${LOGFILECOUNT} time(s) on ${YESTERDAY}:" >>${OUT}
-        echo 'ls /analytics1/logs/stillwell1-${YESTERDAY}*:' >>${OUT}
-        ls /analytics1/logs/stillwell1-${YESTERDAY}* >>${OUT}
-        echo >>${OUT}
-    elif [ ${FAIL} -eq 0 ]; then
-        echo "Stillwell1.bat ran successfully on ${YESTERDAY}" >>${OUT}
-    else
-        echo "Stillwell1.bat failure ${YESTERDAY}" >>${OUT}
+        chown viyadep.viyadep ${OUT}
     fi
-
-    chown viyadep.viyadep ${OUT}
 fi
 
 # EOF:
